# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marques',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('imgpath', models.TextField()),
                ('web', models.TextField()),
            ],
        ),
    ]
